# Generated by Django 4.0 on 2021-12-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tgbot.user')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('description', models.CharField(max_length=120, verbose_name='О себе')),
            ],
        ),
    ]
