# Generated by Django 4.0 on 2021-12-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_alter_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Chat id пользователя'),
        ),
    ]
