# Generated by Django 4.0 on 2021-12-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_alter_profile_city_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фото пользователя'),
        ),
    ]
