# Generated by Django 4.0 on 2021-12-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0010_alter_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Анкета зарегистрирована?'),
        ),
    ]
