# Generated by Django 4.0 on 2021-12-19 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0012_alter_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSearch',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tgbot.user')),
                ('age', models.CharField(default='18-100', max_length=10, verbose_name='Возраст собеседника')),
                ('sex', models.CharField(default='F', max_length=1, verbose_name='Пол собеседника')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tgbot.city')),
            ],
            options={
                'verbose_name': 'Профиль для поиска',
                'verbose_name_plural': 'Профили для поиска',
            },
        ),
    ]
