# Generated by Django 4.0 on 2021-12-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0013_profilesearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='is_basic',
        ),
    ]
