# Generated by Django 4.0 on 2021-12-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0015_profile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
