# Generated by Django 4.0 on 2021-12-31 16:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0018_alter_profilesearch_age_alter_user_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesearch',
            name='unviewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='profilesearch',
            name='viewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None),
        ),
    ]
