# Generated by Django 4.0 on 2021-12-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0019_profilesearch_unviewed_profilesearch_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Chat id пользователя'),
        ),
    ]
