# Generated by Django 4.0 on 2021-12-31 22:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0020_alter_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesearch',
            name='unviewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profilesearch',
            name='viewed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
